### ISSUE TITLE
Appimage version crash 

### ISSUE THREAD

**Issue by K1LL3RPUNCH** [jsnli/Samira#2] opened 2024-11-11 18:16 UTC
Without any error

https://www.youtube.com/watch?v=CQ9V7Vcsvz0

**Comment by jsnli** [comment] 2024-11-11 23:09
Hi, can you try running the appimage from the terminal and share any errors?: `./samira_0.2.0_amd64.AppImage`

**Comment by K1LL3RPUNCH** [comment] 2024-11-15 21:31
> Hi, can you try running the appimage from the terminal and share any errors?: `./samira_0.2.0_amd64.AppImage`

Hi there!
0.3.0 version:

[k1ll3rpunch@archlinux appimage]$ /home/k1ll3rpunch/appimage/samira.appimage 
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API] SteamAPI_Init(): Loaded '/home/k1ll3rpunch/.var/app/com.valvesoftware.Steam/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 489830
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198043030455 [API loaded no]
User Stats Received.
CCrossProcessPipe::BWrite wrote too few bytes: 32 (Обрыв канала).  Continuing.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : Fatal assert; application exiting
src/common/pipes.cpp (883) : Fatal assert; application exiting
11/16 00:30:25 minidumps folder is set to /tmp/dumps
11/16 00:30:25 Init: Installing breakpad exception handler for appid(samira)/version(1.0)/tid(1459)
11/16 00:30:25 ERROR: execv failed when trying to send minidump
11/16 00:30:25 ERROR: Could not run steamerrorreporter binary. Uploading minidump in-process
11/16 00:30:25 Uploading dump (in-process) [url 'https://crash.steampowered.com/submit', proxy '']
/tmp/dumps/assert_20241116003025_3.dmp
11/16 00:30:25 success = no
11/16 00:30:25 error:  /tmp/.mount_samiraPOnaGT/usr/lib/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so)
_ExitOnFatalAssert

**Comment by K1LL3RPUNCH** [comment] 2024-11-15 21:34
Also i can help you with Russian translation, if you need.

**Comment by jsnli** [comment] 2024-11-16 08:11
I ran across this issue briefly before and solved it by updating and restarting the steam client. Please let me know if that works.

Multi-language support is a great idea but may be out of scope for now. Samira will expand in features in the future however and I will keep localization in mind.

**Comment by K1LL3RPUNCH** [comment] 2024-11-16 11:27
> I ran across this issue briefly before and solved it by updating and restarting the steam client. Please let me know if that works.
> 
> Multi-language support is a great idea but may be out of scope for now. Samira will expand in features in the future however and I will keep localization in mind.

I'm using latest flatpak version and Samira from appimage, maybe it is a deal? Can you check it?

**Comment by jsnli** [comment] 2024-11-16 13:19
Flatpak isn't currently supported. For now Samira needs Steam to be installed through pacman or your respective distro's package manager.

**Comment by K1LL3RPUNCH** [comment] 2024-11-16 14:22
> Flatpak isn't currently supported. For now Samira needs to Steam to be installed through pacman or your respective distro's package manager.

But it worked 🤔

**Comment by jsnli** [comment] 2024-11-16 14:58
Yes that's strange, it should have just refused to load the game's achievements outright. Did you previously have Steam installed another way?

**Comment by K1LL3RPUNCH** [comment] 2024-11-16 16:30
> Yes that's strange, it should have just refused to load the game's achievements outright. Did you previously have Steam installed another way?

I think I have a steam-runtime-native, but uninstalled it through -Rscn with all configs, files, etc.

**Comment by jsnli** [comment] 2024-11-16 18:04
I was able to reproduce your error by following these steps on a fresh VM.

1. Install Steam through both pacman and flatpak. This will create two separate installations and folder paths.
2. Run Steam (flatpak) and Samira.
3. Attempt to use Samira functionality after initial game client load and crash.

This is an unintended interaction that isn't supported. Steamworks is probably attempting to use the pacman version and managing to load initial information before inevitably stumbling and crashing. I encourage you to try Steam through pacman until I can provide proper support for flatpak in the future.

**Comment by K1LL3RPUNCH** [comment] 2024-11-16 21:30
> I was able to reproduce your error by following these steps on a fresh VM.
> 
> 1. Install Steam through both pacman and flatpak. This will create two separate installations and folder paths.
> 2. Run Steam (flatpak) and Samira.
> 3. Attempt to use Samira functionality after initial game client load and crash.
> 
> This is an unintended interaction that isn't supported. Steamworks is probably attempting to use the pacman version and managing to load initial information before inevitably stumbling and crashing. I encourage you to try Steam through pacman until I can provide proper support for flatpak in the future.

anyway i hope that helps with flatpak support. maybe i should just to change some settings of flatpak sandboxing.

**Closed as completed** 2024-11-16 23:05 UTC

**Comment by HanPrower** [comment] 2025-02-21 09:54
As a workaround you can extract the AppImage: `samira_0.5.0_amd64.AppImage --appimage-extract`

Then move the contents of the created `squashfs-root` folder to somewhere accessible by the Steam Flatpak.

Next in Steam click the "Games" menu and "Add a Non-Steam Game to my Library..." and locate the above folder, change the view to all files, and select `AppRun`.

Find `AppRun` in your Game Library (feel free to right click and Properties to rename it). Run it like any other game/app. Profit? 😅

As a note: Steam Flatpak can't run AppImages directly as it doesn't have `fusermount`: https://github.com/flathub/com.valvesoftware.Steam/issues/770

---

Alternatively, from the above - I had this brainwave just as I walked away from my computer - you can move the `samira.AppImage` to a location Steam Flatpak can access and then add the AppImage directly and then right click > Properties and add in the "Launch Options": `--appimage-extract-and-run`

If you use Samira a lot though, this could be a lot of extracting, running, deleting.
